version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47
